// Placeholder content: replace with real posts.
// All authors are fictional; titles, dates and read times are samples only.
//
// Shape: { id, title, excerpt, category, date, readTime, author, image, href, featured }
// - category must be one of CATEGORIES (except 'All Posts') so the chips can match it
// - image: imported asset or /public path, or null for the grid-pattern placeholder
// - href: '#blogs' until blog detail pages exist
export const ALL = 'All Posts'

export const CATEGORIES = [ALL, 'Web Dev', 'AI / ML', 'Open Source', 'Career Growth', 'DevOps', 'UX Design']

export const POSTS = [
  {
    id: 'first-full-stack-app',
    title: 'Shipping My First Full-Stack App from Coimbatore',
    excerpt: 'From a blank folder to a deployed React and Node app: what I planned, what broke and what I would do differently.',
    category: 'Web Dev',
    date: 'Apr 26, 2025',
    readTime: '8 min',
    author: 'Kavya Ramesh',
    image: null,
    href: '#blogs',
    featured: true,
  },
  {
    id: 'first-open-source-pr',
    title: 'My First Open Source Pull Request',
    excerpt: 'How I found a beginner-friendly issue, read an unfamiliar codebase and got my first PR merged.',
    category: 'Open Source',
    date: 'Apr 18, 2025',
    readTime: '6 min',
    author: 'Meera Sundar',
    image: null,
    href: '#blogs',
    featured: false,
  },
  {
    id: 'ml-for-beginners',
    title: 'Machine Learning for Absolute Beginners',
    excerpt: 'A gentle walk through training your first model in Python, with no maths degree required.',
    category: 'AI / ML',
    date: 'Apr 10, 2025',
    readTime: '10 min',
    author: 'Nila Arunachalam',
    image: null,
    href: '#blogs',
    featured: false,
  },
  {
    id: 'career-switch-to-tech',
    title: 'Switching Careers into Tech at 30',
    excerpt: 'Notes on learning to code alongside a full-time job, building a portfolio and preparing for interviews.',
    category: 'Career Growth',
    date: 'Mar 29, 2025',
    readTime: '7 min',
    author: 'Divya Krishnan',
    image: null,
    href: '#blogs',
    featured: false,
  },
  {
    id: 'devops-basics',
    title: 'DevOps Basics: CI/CD Without the Jargon',
    excerpt: 'What a pipeline actually does, explained with one small project and a single workflow file.',
    category: 'DevOps',
    date: 'Mar 21, 2025',
    readTime: '9 min',
    author: 'Lakshmi Venkat',
    image: null,
    href: '#blogs',
    featured: false,
  },
  {
    id: 'ux-case-study-bus-app',
    title: 'UX Case Study: Redesigning a Local Bus Timetable App',
    excerpt: 'User interviews, paper sketches and three rounds of testing on a tool used every day by commuters.',
    category: 'UX Design',
    date: 'Mar 12, 2025',
    readTime: '11 min',
    author: 'Anjali Murugan',
    image: null,
    href: '#blogs',
    featured: false,
  },
  {
    id: 'accessible-forms',
    title: 'Building Accessible Forms in React',
    excerpt: 'Labels, error messages and keyboard support: small habits that make forms work for everyone.',
    category: 'Web Dev',
    date: 'Mar 3, 2025',
    readTime: '5 min',
    author: 'Priya Selvam',
    image: null,
    href: '#blogs',
    featured: false,
  },
  {
    id: 'tamil-nlp-dataset',
    title: 'Cleaning a Tamil Text Dataset for NLP',
    excerpt: 'Handling mixed scripts, transliteration and noisy text before training a simple classifier.',
    category: 'AI / ML',
    date: 'Feb 22, 2025',
    readTime: '12 min',
    author: 'Revathi Kannan',
    image: null,
    href: '#blogs',
    featured: false,
  },
  {
    id: 'finding-a-mentor',
    title: 'Finding a Mentor (and Being One)',
    excerpt: 'How to ask for guidance, what to bring to a first conversation and why mentoring others helps you grow.',
    category: 'Career Growth',
    date: 'Feb 14, 2025',
    readTime: '6 min',
    author: 'Sowmya Ilango',
    image: null,
    href: '#blogs',
    featured: false,
  },
]
